// <auto-generated />
using System;
using API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.BatchClass", b =>
                {
                    b.Property<string>("TokenKelas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nchar(7)")
                        .HasColumnName("token_kelas");

                    b.Property<string>("JenisKelas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaBatch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoBatch")
                        .HasColumnType("int");

                    b.Property<string>("PIC")
                        .IsRequired()
                        .HasColumnType("nchar(5)");

                    b.HasKey("TokenKelas");

                    b.HasIndex("PIC");

                    b.ToTable("tb_m_batchclass");
                });

            modelBuilder.Entity("API.Models.Employee", b =>
                {
                    b.Property<string>("NIK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nchar(5)")
                        .HasColumnName("nik");

                    b.Property<DateTime?>("BirthDate")
                        .IsRequired()
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("first_name");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("id_role");

                    b.HasKey("NIK");

                    b.HasAlternateKey("Email");

                    b.ToTable("tb_m_employee");
                });

            modelBuilder.Entity("API.Models.Materi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescMateri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desc_materi");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaMateri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenKelas")
                        .IsRequired()
                        .HasColumnType("nchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("TokenKelas");

                    b.ToTable("tb_m_materi");
                });

            modelBuilder.Entity("API.Models.Participant", b =>
                {
                    b.Property<string>("NIK")
                        .HasColumnType("nchar(5)")
                        .HasColumnName("nik");

                    b.Property<int>("FinalScore")
                        .HasColumnType("int");

                    b.Property<string>("IdBatchClass")
                        .IsRequired()
                        .HasColumnType("nchar(7)");

                    b.HasKey("NIK");

                    b.HasIndex("IdBatchClass");

                    b.ToTable("tb_m_participant");
                });

            modelBuilder.Entity("API.Models.ParticipantTugas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdPeserta")
                        .IsRequired()
                        .HasColumnType("nchar(5)");

                    b.Property<int>("IdTugas")
                        .HasColumnType("int");

                    b.Property<string>("NamaFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nilai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPeserta");

                    b.HasIndex("IdTugas");

                    b.ToTable("tb_r_participanttugas");
                });

            modelBuilder.Entity("API.Models.Tugas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescTugas")
                        .HasColumnType("text")
                        .HasColumnName("desc_tugas");

                    b.Property<int>("IdMateri")
                        .HasColumnType("int");

                    b.Property<string>("Judul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaTugas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdMateri");

                    b.ToTable("tb_m_tugas");
                });

            modelBuilder.Entity("API.Models.BatchClass", b =>
                {
                    b.HasOne("API.Models.Employee", "Employee")
                        .WithMany("BatchClass")
                        .HasForeignKey("PIC")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("API.Models.Materi", b =>
                {
                    b.HasOne("API.Models.BatchClass", "BatchClass")
                        .WithMany("Materi")
                        .HasForeignKey("TokenKelas")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BatchClass");
                });

            modelBuilder.Entity("API.Models.Participant", b =>
                {
                    b.HasOne("API.Models.BatchClass", "BatchClass")
                        .WithMany("Participant")
                        .HasForeignKey("IdBatchClass")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("API.Models.Employee", "Employee")
                        .WithOne("Participant")
                        .HasForeignKey("API.Models.Participant", "NIK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BatchClass");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("API.Models.ParticipantTugas", b =>
                {
                    b.HasOne("API.Models.Participant", "Participant")
                        .WithMany("ParticipantTugas")
                        .HasForeignKey("IdPeserta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("API.Models.Tugas", "Tugas")
                        .WithMany("ParticipantTugas")
                        .HasForeignKey("IdTugas")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Tugas");
                });

            modelBuilder.Entity("API.Models.Tugas", b =>
                {
                    b.HasOne("API.Models.Materi", "Materi")
                        .WithMany("Tugas")
                        .HasForeignKey("IdMateri")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Materi");
                });

            modelBuilder.Entity("API.Models.BatchClass", b =>
                {
                    b.Navigation("Materi");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("API.Models.Employee", b =>
                {
                    b.Navigation("BatchClass");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("API.Models.Materi", b =>
                {
                    b.Navigation("Tugas");
                });

            modelBuilder.Entity("API.Models.Participant", b =>
                {
                    b.Navigation("ParticipantTugas");
                });

            modelBuilder.Entity("API.Models.Tugas", b =>
                {
                    b.Navigation("ParticipantTugas");
                });
#pragma warning restore 612, 618
        }
    }
}
